### PR TITLE
Added Freehand settings

### PR DESCRIPTION
**Pull request by awenger**
- Added support for freehand settings that must be applied before the img input (e.x. density for pdf)
- Changes options() to operations()

### CODE REVIEW

**Comment by ebaizel** [comment]
great pull request.  i wrote something similar for myself to get the -composite working which has a syntax like:
```
convert -gravity Center -composite <input_stream> /tmp/overlay.png <output_stream>
```

**Comment by awenger** [comment]
Thanks, seems there are more cases that require passing options in front of the input stream.
The disadvantage of this pr is the changed api (```options()``` -> ```operations()```). I tried to point out the difference of settings and operations.

**Comment by ebaizel** [comment]
makes sense to separate settings and operations.  so how do we proceed from here?  i was going to fork the repo and use my own, but would much rather work off of a common library.

@eivindfjeldstad what are your thoughts on this?

**Comment by eivindfjeldstad** [comment]
thanks

**Comment by ebaizel** [comment]
thanks!

**Pull request merged**
